export const categories = [
  { id: 'all', name: 'الكل', icon: '🛒' },
  { id: 'lamb', name: 'الخروف', icon: '🐑', image: '/images/lamb/حري.png' },
  { id: 'chicken', name: 'الدجاج', icon: '🍗', image: '/images/chicken/صدور دجاج.png' },
  { id: 'veggies', name: 'خضروات وفواكه', icon: '🥗', image: '/images/vegetables/طماطم.png' },
];

export const products = [
  // الخروف (Lamb) - 7 منتجات
  {
    id: 1,
    name: "تيس",
    category: "lamb",
    price: 950,
    unit: "ذبيحة",
    image: "/images/lamb/تيس.png",
    description: "تيس بلدي ممتاز، لحم طري وشهي، مثالي للولائم والمناسبات.",
    badge: "مميز",
    size: "متوسط",
    weight: "18-22 كجم",
    isFeatured: true,
    imageObjectPosition: "object-[50%_25%]",
  },
  {
    id: 2,
    name: "جذع فاخر تميمة",
    category: "lamb",
    price: 1200,
    unit: "ذبيحة",
    image: "/images/lamb/جذع فاخر تميمة.png",
    description: "جذع فاخر خاص للتميمة والعقيقة، أفضل جودة ممكنة.",
    badge: "فاخر",
    size: "كبير",
    weight: "24-28 كجم",
    isFeatured: true,
  },
  {
    id: 3,
    name: "حري",
    category: "lamb",
    price: 1100,
    unit: "ذبيحة",
    image: "/images/lamb/حري.png",
    description: "خروف حري بلدي من أجود الأنواع، لحم طازج وممتاز.",
    badge: "جديد",
    size: "كبير",
    weight: "22-26 كجم",
    isFeatured: true,
    imageObjectPosition: "object-[50%_25%]",
  },
  {
    id: 4,
    name: "خروف نعيمي صغير",
    category: "lamb",
    price: 850,
    unit: "ذبيحة",
    image: "/images/lamb/خروف نعيمي صغير.png",
    description: "خروف نعيمي صغير، لحم طري ولذيذ، مناسب للعائلات الصغيرة.",
    badge: "العرض الأفضل",
    size: "صغير",
    weight: "14-17 كجم",
    isFeatured: false,
  },
  {
    id: 5,
    name: "خروف نعيمي كبير",
    category: "lamb",
    price: 1350,
    unit: "ذبيحة",
    image: "/images/lamb/خروف نعيمي كبير.png",
    description: "خروف نعيمي كبير الحجم، مثالي للمناسبات الكبرى.",
    badge: "الأكثر مبيعاً",
    size: "كبير جداً",
    weight: "26-30 كجم",
    isFeatured: true,
  },
  {
    id: 6,
    name: "خروف نعيمي متوسط",
    category: "lamb",
    price: 1050,
    unit: "ذبيحة",
    image: "/images/lamb/خروف نعيمي متوسط.png",
    description: "خروف نعيمي متوسط الحجم، الخيار الأمثل للجميع.",
    badge: "مفضل",
    size: "متوسط",
    weight: "19-23 كجم",
    isFeatured: true,
  },
  {
    id: 7,
    name: "نعيمي لباني",
    category: "lamb",
    price: 750,
    unit: "ذبيحة",
    image: "/images/lamb/نعيمي لباني.png",
    description: "خروف نعيمي لباني (رضيع)، لحم فائق النعومة والطراوة.",
    badge: "حصري",
    size: "صغير جداً",
    weight: "10-13 كجم",
    isFeatured: false,
  },

  // الدجاج (Chicken) - 3 منتجات
  {
    id: 8,
    name: "صدور دجاج",
    category: "chicken",
    price: 35,
    unit: "طبق",
    image: "/images/chicken/صدور دجاج.png",
    description: "صدور دجاج طازجة صافية، خالية من العظم، مثالية للطهي الصحي.",
    badge: "طازج",
    isFeatured: true,
  },
  {
    id: 9,
    name: "دبوس دجاج",
    category: "chicken",
    price: 25,
    unit: "طبق",
    image: "/images/chicken/دبوس دجاج.png",
    description: "أفخاذ دجاج (دبوس) طازجة، ممتازة للقلي والشواء.",
    badge: "الأفضل",
    isFeatured: true,
  },
  {
    id: 10,
    name: "بكج مكس",
    category: "chicken",
    price: 45,
    unit: "بكج",
    image: "/images/chicken/بكج مكس.png",
    description: "تشكيلة مميزة من الدجاج الطازج (مكس) تناسب جميع الاذواق.",
    badge: "توفير",
    isFeatured: true,
  },

  // خضروات وفواكه (Vegetables & Fruits) - 32 منتج
  {
    id: 11,
    name: "أناناس",
    category: "veggies",
    price: 18,
    unit: "حبة",
    image: "/images/vegetables/أناناس.png",
    description: "أناناس طازج حلو المذاق، غني بالفيتامينات.",
    badge: "استوائي",
    isFeatured: true,
  },
  {
    id: 12,
    name: "أفوكادو",
    category: "veggies",
    price: 15,
    unit: "حبة",
    image: "/images/vegetables/افوكادو.png",
    description: "أفوكادو طازج، مثالي للسلطات والعصائر الصحية.",
    badge: "صحي",
    isFeatured: true,
  },
  {
    id: 13,
    name: "باذنجان",
    category: "veggies",
    price: 5,
    unit: "كجم",
    image: "/images/vegetables/باذنجان.png",
    description: "باذنجان بلدي طازج، ممتاز للطبخ والشواء.",
    badge: "بلدي",
    isFeatured: false,
  },
  {
    id: 14,
    name: "بامية",
    category: "veggies",
    price: 12,
    unit: "كجم",
    image: "/images/vegetables/بامية.png",
    description: "بامية طازجة خضراء، مثالية للطبخات التقليدية.",
    badge: "موسمي",
    isFeatured: false,
  },
  {
    id: 15,
    name: "بخارى",
    category: "veggies",
    price: 22,
    unit: "كجم",
    image: "/images/vegetables/بخارى.png",
    description: "برقوق طازج حلو المذاق، غني بالألياف.",
    badge: "حلو",
    isFeatured: false,
  },
  {
    id: 16,
    name: "برتقال",
    category: "veggies",
    price: 8,
    unit: "كجم",
    image: "/images/vegetables/برتقال.png",
    description: "برتقال طازج عصيري، مليء بفيتامين C.",
    badge: "عصير",
    isFeatured: true,
  },
  {
    id: 17,
    name: "بصل",
    category: "veggies",
    price: 3,
    unit: "كجم",
    image: "/images/vegetables/بصل.png",
    description: "بصل أحمر طازج، أساسي في كل مطبخ.",
    badge: "أساسي",
    isFeatured: false,
  },
  {
    id: 18,
    name: "بطاطة",
    category: "veggies",
    price: 4,
    unit: "كجم",
    image: "/images/vegetables/بطاطة.png",
    description: "بطاطس بلدية ممتازة للقلي والطبخ.",
    badge: "بلدي",
    isFeatured: false,
  },
  {
    id: 19,
    name: "بطيخ",
    category: "veggies",
    price: 6,
    unit: "كجم",
    image: "/images/vegetables/بطيخ.png",
    description: "بطيخ أحمر طازج ومنعش، مثالي للصيف.",
    badge: "منعش",
    isFeatured: true,
  },
  {
    id: 20,
    name: "تفاح أخضر",
    category: "veggies",
    price: 10,
    unit: "كجم",
    image: "/images/vegetables/تفاح أخضر.png",
    description: "تفاح أخضر مقرمش حامض قليلاً، صحي ولذيذ.",
    badge: "مقرمش",
    isFeatured: false,
  },
  {
    id: 21,
    name: "تفاح أحمر",
    category: "veggies",
    price: 12,
    unit: "كجم",
    image: "/images/vegetables/تفاح احمر.png",
    description: "تفاح أحمر سكري طازج، الأفضل للعائلة.",
    badge: "سكري",
    isFeatured: true,
  },
  {
    id: 22,
    name: "جزر",
    category: "veggies",
    price: 4,
    unit: "كجم",
    image: "/images/vegetables/جزر.png",
    description: "جزر طازج برتقالي اللون، غني بالفيتامينات.",
    badge: "صحي",
    isFeatured: false,
  },
  {
    id: 23,
    name: "جنزبيل",
    category: "veggies",
    price: 25,
    unit: "كجم",
    image: "/images/vegetables/جنزبيل.png",
    description: "زنجبيل طازج، مثالي للشاي والطبخ العلاجي.",
    badge: "علاجي",
    isFeatured: false,
  },
  {
    id: 24,
    name: "خس",
    category: "veggies",
    price: 5,
    unit: "حبة",
    image: "/images/vegetables/خس.png",
    description: "خس طازج مقرمش، أساسي للسلطات الصحية.",
    badge: "طازج",
    isFeatured: false,
  },
  {
    id: 25,
    name: "خوخ",
    category: "veggies",
    price: 18,
    unit: "كجم",
    image: "/images/vegetables/خوخ.png",
    description: "خوخ طازج حلو وعصيري، فاكهة الصيف المفضلة.",
    badge: "موسمي",
    isFeatured: false,
  },
  {
    id: 26,
    name: "خيار",
    category: "veggies",
    price: 5,
    unit: "كجم",
    image: "/images/vegetables/خيار.png",
    description: "خيار طازج ومقرمش، منعش ومرطب.",
    badge: "منعش",
    isFeatured: false,
  },
  {
    id: 27,
    name: "رمان",
    category: "veggies",
    price: 16,
    unit: "كجم",
    image: "/images/vegetables/رمان .png",
    description: "رمان أحمر حلو المذاق، غني بمضادات الأكسدة.",
    badge: "مميز",
    isFeatured: true,
  },
  {
    id: 28,
    name: "شمام",
    category: "veggies",
    price: 7,
    unit: "كجم",
    image: "/images/vegetables/شمام.png",
    description: "شمام حلو ومنعش، مثالي لأيام الصيف الحارة.",
    badge: "حلو",
    isFeatured: false,
  },
  {
    id: 29,
    name: "طماطم شيري",
    category: "veggies",
    price: 14,
    unit: "كجم",
    image: "/images/vegetables/طماطم شيري.png",
    description: "طماطم شيري صغيرة الحجم، حلوة ولذيذة.",
    badge: "صغير",
    isFeatured: false,
  },
  {
    id: 30,
    name: "طماطم",
    category: "veggies",
    price: 6,
    unit: "كجم",
    image: "/images/vegetables/طماطم.png",
    description: "طماطم بلدية طازجة، أساسية في كل طبخة.",
    badge: "أساسي",
    isFeatured: false,
  },
  {
    id: 31,
    name: "عنب أخضر",
    category: "veggies",
    price: 20,
    unit: "كجم",
    image: "/images/vegetables/عنب اخضر.png",
    description: "عنب أخضر حلو بدون بذور، لذيذ ومنعش.",
    badge: "بدون بذور",
    isFeatured: true,
  },
  {
    id: 32,
    name: "عنب أسود",
    category: "veggies",
    price: 22,
    unit: "كجم",
    image: "/images/vegetables/عنب اسود .png",
    description: "عنب أسود فاخر حلو المذاق، غني بمضادات الأكسدة.",
    badge: "فاخر",
    isFeatured: true,
  },
  {
    id: 33,
    name: "فراولة",
    category: "veggies",
    price: 28,
    unit: "كجم",
    image: "/images/vegetables/فراولة.png",
    description: "فراولة طازجة حلوة وعطرة، الأفضل للحلويات.",
    badge: "موسمي",
    isFeatured: true,
  },
  {
    id: 34,
    name: "فلفل أحمر",
    category: "veggies",
    price: 8,
    unit: "كجم",
    image: "/images/vegetables/فلفل احمر.png",
    description: "فلفل أحمر حار، يضيف نكهة قوية للطبخات.",
    badge: "حار",
    isFeatured: false,
  },
  {
    id: 35,
    name: "فلفل بارد أخضر",
    category: "veggies",
    price: 6,
    unit: "كجم",
    image: "/images/vegetables/فلفل بارد اخضر.png",
    description: "فلفل أخضر بارد، مثالي للسلطات والطبخ.",
    badge: "بارد",
    isFeatured: false,
  },
  {
    id: 36,
    name: "فلفل رومي ملون",
    category: "veggies",
    price: 10,
    unit: "كجم",
    image: "/images/vegetables/فلفل رومي ملون.png",
    description: "فلفل رومي ملون (أحمر، أصفر، أخضر)، حلو ولذيذ.",
    badge: "ملون",
    isFeatured: true,
  },
  {
    id: 37,
    name: "كوسة",
    category: "veggies",
    price: 5,
    unit: "كجم",
    image: "/images/vegetables/كوسة.png",
    description: "كوسة خضراء طازجة، خفيفة وصحية.",
    badge: "صحي",
    isFeatured: false,
  },
  {
    id: 38,
    name: "كيوي",
    category: "veggies",
    price: 20,
    unit: "كجم",
    image: "/images/vegetables/كيوي.png",
    description: "كيوي طازج غني بفيتامين C، لذيذ ومنعش.",
    badge: "استوائي",
    isFeatured: false,
  },
  {
    id: 39,
    name: "ليمون",
    category: "veggies",
    price: 7,
    unit: "كجم",
    image: "/images/vegetables/ليمون.png",
    description: "ليمون طازج حامض، أساسي للطبخ والعصائر.",
    badge: "حامض",
    isFeatured: false,
  },
  {
    id: 40,
    name: "مانجة",
    category: "veggies",
    price: 24,
    unit: "كجم",
    image: "/images/vegetables/مانجة.png",
    description: "مانجة استوائية حلوة وعصيرية، ملكة الفواكه.",
    badge: "ملكة",
    isFeatured: true,
  },
  {
    id: 41,
    name: "موز",
    category: "veggies",
    price: 7,
    unit: "كجم",
    image: "/images/vegetables/موز.png",
    description: "موز طازج غني بالبوتاسيوم، مثالي للإفطار.",
    badge: "طاقة",
    isFeatured: false,
  },
  {
    id: 42,
    name: "يوسف أفندي",
    category: "veggies",
    price: 9,
    unit: "كجم",
    image: "/images/vegetables/يوسف افندي.png",
    description: "يوسف أفندي (ماندرين) حلو وسهل التقشير.",
    badge: "حلو",
    isFeatured: false,
  },
];

export const heroImage = "/images/lamb/حري.png";
