-- SUPPORT ADVANCED MARKETING FEATURES
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS user_tier TEXT DEFAULT 'all';
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS applicable_products TEXT DEFAULT 'all';

ALTER TABLE offers ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(id);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'banner';
